### ISSUE TITLE
Failed to run with sonarqube 7.6

### ISSUE THREAD

**Issue by lancerdima** [Facthunder/sonar-branch-plugin#1]
Deployed extension to SonarQube 7.6.
SonarQube won't start with error in web.log:

> 2019.02.20 18:23:23 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin SonarQube Branch Plugin [branch]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:573)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/server/branch/BranchFeatureExtension
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at io.facthunder.sonar.branch.BranchPlugin.define(BranchPlugin.java:52)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.server.branch.BranchFeatureExtension
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 24 common frames omitted
2019.02.20 18:23:24 INFO  web[][o.s.p.StopWatcher] Stopping process

**Comment by begarco** [comment]
Sorry but this plugin is not supported since SonarQube 7.2.

In fact, it is based on official branch plugin. Since version 7.2, SonarQube has changed its management of branch feature: it is no more enabled through plugin, so that this plugin is no more effective since 7.2.

Sorry.

**Comment by mc1arke** [comment]
Sonarqube 7.4 and above is supported by the new [SonarQube Community Branch Plugin](https://github.com/mc1arke/sonarqube-community-branch-plugin). Give it a shot and give any feedback on that repository.

**Comment by begarco** [comment]
I do not know this community plugin and mc1arke is not a member of our project:you can try its plugin at your own risks. I close this issue.
